spring.application.name=SecurityApplication
spring.datasource.url=${URL}
spring.datasource.username=${USERNAME}
spring.datasource.password=${PASSWORD}
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#security configs
#spring.security.user.name=${USERNAME}
#spring.security.user.password={PASSWORD}