# App name
spring.application.name=SecurityApplication

# Database config (replace with your own values)
spring.datasource.url=jdbc:mysql://localhost:3306/YOUR_DB_NAME?useSSL=false
spring.datasource.username=YOUR_DB_USERNAME
spring.datasource.password=YOUR_DB_PASSWORD

# JPA config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT (replace with your own secret)
jwt.secretKey=YOUR_SECRET_KEY

# Environment
deploy.env=development